# Generated by Django 2.2.7 on 2019-11-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='citizenship_image',
            field=models.ImageField(blank=True, upload_to='id_image'),
        ),
    ]
